services:
  streamscheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamscheduler
    ports:
      - "7575:7575"
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=7575
      - JWT_SECRET=${JWT_SECRET}
